services:
  competencye-postgres:
    image: postgres:18.1
    container_name: competency-postgres
    environment:
      POSTGRES_DB: competencymatrix
      POSTGRES_USER: competency
      POSTGRES_PASSWORD: competency
    ports:
      - "5432:5432"
    volumes:
      # This is the new (Postgres 18+ location)
      - competency_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U competency -d competencymatrix"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  competency_postgres_data:
