spring:
  application:
    name: competency-matrix
  datasource:
    url: jdbc:postgresql://localhost:5432/competencymatrix
    username: competency
    password: competency
    driver-class-name: org.postgresql.Driver
  test:
    print-condition-evaluation-report: false


server:
  port: 8080

management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: health,prometheus,liveness,readiness
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always



logging:
  level:
    nl.leonw.competencymatrix: DEBUG
    org.springframework.jdbc: DEBUG
#    org.testcontainers: DEBUG
#    com.github.dockerjava: DEBUG
#    org.springframework.boot.testcontainers: DEBUG
